"use client";

import { useState } from "react";
import { Loader2, FileText } from "lucide-react";
import { toast } from "sonner";
import { AdminCVAnalysis, AdminInterview } from "@/types";

interface DownloadActionButtonProps {
  type: "analysis" | "interview";
  data: AdminCVAnalysis | AdminInterview;
}

export default function DownloadActionButton({
  type,
  data,
}: DownloadActionButtonProps) {
  const [loading, setLoading] = useState(false);

  const handleDownload = () => {
    try {
      setLoading(true);

      let content = "";
      let filename = "";

      if (type === "analysis") {
        const item = data as AdminCVAnalysis;
        filename = `Analiz_Raporu_${
          item.cv?.user?.email?.split("@")[0] || "Aday"
        }_${new Date().toISOString().split("T")[0]}.txt`;

        content = `
================================================================
                    CAREER AI - CV ANALİZ RAPORU
================================================================

Tarih: ${new Date(item.createdAt).toLocaleString("tr-TR")}
Aday: ${item.cv?.user?.email || "Bilinmiyor"}
Başlık: ${item.cv?.title || "Başlıksız CV"}
Analiz ID: ${item.id}

----------------------------------------------------------------
1. GENEL DEĞERLENDİRME
----------------------------------------------------------------
Genel Puan: ${item.score}/100

Özet:
${item.summary}

Anahtar Yetkinlikler:
${
  Array.isArray(item.keywords)
    ? item.keywords.map((k) => `• ${k}`).join("\n")
    : "Belirtilmemiş"
}

----------------------------------------------------------------
2. DETAYLI METRİKLER
----------------------------------------------------------------
• Etki (Impact):      ${item.impact}/100
• Kısalık (Brevity):  ${item.brevity}/100
• ATS Uyumu:          ${item.ats}/100
• Stil ve Ton:        ${item.style}/100

----------------------------------------------------------------
3. GELİŞİM ÖNERİSİ
----------------------------------------------------------------
${item.suggestion}

================================================================
Generated by CareerAI Platform
================================================================
        `.trim();
      } else {
        const item = data as AdminInterview;
        filename = `Mulakat_Kaydi_${item.position.replace(/\s+/g, "_")}_${
          new Date().toISOString().split("T")[0]
        }.txt`;

        const messages = item.messages || [];
        const duration =
          messages.length > 0
            ? Math.floor(
                (new Date(messages[messages.length - 1].createdAt).getTime() -
                  new Date(messages[0].createdAt).getTime()) /
                  60000
              )
            : 0;

        content = `
================================================================
                  CAREER AI - MÜLAKAT SİMÜLASYONU
================================================================

Tarih: ${new Date(item.date).toLocaleString("tr-TR")}
Pozisyon: ${item.position}
Aday: ${item.user?.email || "Bilinmiyor"}
Süre: ~${duration} dakika
Toplam Mesaj: ${messages.length}

----------------------------------------------------------------
MÜLAKAT AKIŞI
----------------------------------------------------------------

${messages
  .map(
    (m) => `
[${m.role === "ASSISTANT" ? "AI MÜLAKATÇI" : "ADAY"}] - ${new Date(
      m.createdAt
    ).toLocaleTimeString("tr-TR")}
${m.content}
----------------------------------------------------------------
`
  )
  .join("")}

================================================================
Generated by CareerAI Platform
================================================================
        `.trim();
      }

      // Dosya indirme işlemi
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

      toast.success("Rapor başarıyla indirildi.");
    } catch (error) {
      console.error(error);
      toast.error("İndirme sırasında bir hata oluştu.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={loading}
      title="Raporu İndir"
      className="p-1.5 text-slate-400 hover:text-indigo-400 hover:bg-indigo-500/10 rounded-lg transition-all group"
    >
      {loading ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <FileText className="w-4 h-4 group-hover:scale-110 transition-transform" />
      )}
    </button>
  );
}
